---
- hosts: all
  
  tasks:
  - name: Run UPdate
    shell: |
     yum update -y

  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - yum-utils
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  - name: Copying required files
    shell: |
     yum update -y
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum-config-manager --enable docker-ce-nightly
     yum-config-manager --enable docker-ce-test 
     systemctl start docker
...